"""add new tabe

Revision ID: 2376ff18bd8a
Revises: 40cae73c75dc
Create Date: 2026-06-03 21:48:18.026695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2376ff18bd8a'
down_revision: Union[str, Sequence[str], None] = '40cae73c75dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('change', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('agents_count', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('duration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'duration')
    op.drop_column('reports', 'agents_count')
    op.drop_column('reports', 'change')
    # ### end Alembic commands ###
