"""add null label for report col

Revision ID: 9e04cb2e2990
Revises: 2376ff18bd8a
Create Date: 2026-06-04 10:52:49.736534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e04cb2e2990"
down_revision: Union[str, Sequence[str], None] = "2376ff18bd8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_forecasts") as batch_op:
        batch_op.alter_column(
            "price_low",
            existing_type=sa.Float(),
            nullable=True,
        )

        batch_op.alter_column(
            "price_high",
            existing_type=sa.Float(),
            nullable=True,
        )

        batch_op.alter_column(
            "price_target",
            existing_type=sa.Float(),
            nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_forecasts") as batch_op:
        batch_op.alter_column(
            "price_target",
            existing_type=sa.Float(),
            nullable=False,
        )

        batch_op.alter_column(
            "price_high",
            existing_type=sa.Float(),
            nullable=False,
        )

        batch_op.alter_column(
            "price_low",
            existing_type=sa.Float(),
            nullable=False,
        )
    # ### end Alembic commands ###
