"""add job col

Revision ID: e761bb5d2edc
Revises: 9e04cb2e2990
Create Date: 2026-06-04 12:53:00.715819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e761bb5d2edc'
down_revision: Union[str, Sequence[str], None] = '9e04cb2e2990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'config')
    # ### end Alembic commands ###
