from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from app.routers.v1.jobs.models.relational import Job
from app.routers.v1.jobs.schemas.job import JobCreate, JobUpdate
from typing import List, Optional

class JobRepository:
    def __init__(self, db: AsyncSession):
        self.db = db

    async def get_jobs(self, user_id: int) -> List[Job]:
        stmt = select(Job).where(Job.user_id == user_id).order_by(Job.created_at.desc())
        result = await self.db.execute(stmt)
        return list(result.scalars().all())

    async def get_job(self, job_id: int, user_id: int) -> Optional[Job]:
        stmt = select(Job).where(Job.id == job_id, Job.user_id == user_id)
        result = await self.db.execute(stmt)
        return result.scalars().first()

    async def create_job(self, user_id: int, job_in: JobCreate) -> Job:
        job_data = job_in.model_dump()
        db_job = Job(
            user_id=user_id,
            **job_data
        )
        self.db.add(db_job)
        await self.db.commit()
        await self.db.refresh(db_job)
        return db_job

    async def update_job(self, job_id: int, user_id: int, job_in: JobUpdate) -> Optional[Job]:
        db_job = await self.get_job(job_id, user_id)
        if not db_job:
            return None

        update_data = job_in.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            setattr(db_job, field, value)

        await self.db.commit()
        await self.db.refresh(db_job)
        return db_job

    async def delete_job(self, job_id: int, user_id: int) -> bool:
        db_job = await self.get_job(job_id, user_id)
        if not db_job:
            return False
            
        await self.db.delete(db_job)
        await self.db.commit()
        return True

    async def get_job_metrics(self, user_id: int):
        from sqlalchemy import func
        from app.routers.v1.agent_reports.models.relational import Report

        # Real queries to get metrics for the user's jobs
        # Active jobs
        stmt_active = select(func.count(Job.id)).where(Job.user_id == user_id, Job.status == "active")
        active_jobs = await self.db.scalar(stmt_active) or 0

        # Completed reports generated by jobs
        stmt_reports = select(func.count(Report.id)).where(
            Report.user_id == user_id, 
            Report.job_id.is_not(None)
        )
        total_reports = await self.db.scalar(stmt_reports) or 0

        # Failed reports generated by jobs
        stmt_failed = select(func.count(Report.id)).where(
            Report.user_id == user_id, 
            Report.job_id.is_not(None),
            Report.status == "failed"
        )
        failed_reports = await self.db.scalar(stmt_failed) or 0

        return {
            "active_jobs": active_jobs,
            "total_reports": total_reports,
            "failed_reports": failed_reports
        }

    async def get_job_history(self, job_id: int) -> List[str]:
        from app.routers.v1.agent_reports.models.relational import Report
        stmt = select(Report.status).where(Report.job_id == job_id).order_by(Report.report_date.desc()).limit(7)
        result = await self.db.execute(stmt)
        statuses = result.scalars().all()
        # Ensure we always return exactly 7 items (pad with 'none' if fewer)
        history = list(statuses)
        # Convert running to none, or completed to success, etc. for UI mapping
        mapped_history = []
        for s in history:
            if s == "completed":
                mapped_history.append("success")
            elif s == "failed":
                mapped_history.append("failed")
            elif s == "warning":
                mapped_history.append("warning")
            else:
                mapped_history.append("none")

        mapped_history.reverse() # Oldest first, newest last
        while len(mapped_history) < 7:
            mapped_history.insert(0, "none")

        return mapped_history

    async def get_history_map(self, job_ids: List[int], per_job: int = 7) -> dict:
        """History đã map cho nhiều job trong 1 query (tránh N+1).

        Trả về ``{job_id: [status_mapped_x7]}`` — mỗi job đủ 7 phần tử
        (pad "none"), thứ tự cũ → mới như ``get_job_history``.
        """
        from sqlalchemy import func
        from app.routers.v1.agent_reports.models.relational import Report

        if not job_ids:
            return {}
        # Row number theo report_date giảm dần trong từng job, rồi giữ top N.
        row_num = (
            func.row_number()
            .over(
                partition_by=Report.job_id,
                order_by=Report.report_date.desc(),
            )
            .label("rn")
        )
        subq = (
            select(Report.job_id, Report.status, row_num)
            .where(Report.job_id.in_(job_ids))
            .subquery()
        )
        stmt = (
            select(subq.c.job_id, subq.c.status)
            .where(subq.c.rn <= per_job)
            .order_by(subq.c.job_id, subq.c.rn)
        )
        result = await self.db.execute(stmt)

        mapped: dict = {}
        for job_id, status in result.all():
            if status == "completed":
                s = "success"
            elif status == "failed":
                s = "failed"
            elif status == "warning":
                s = "warning"
            else:
                s = "none"
            mapped.setdefault(job_id, []).append(s)
        # Chuẩn hoá: reverse (cũ → mới) + pad đúng per_job phần tử.
        out = {jid: (list(reversed(mapped.get(jid, []))) + ["none"] * per_job)[:per_job]
               for jid in job_ids}
        return out

    async def get_last_run_map(self, job_ids: List[int]) -> dict:
        """Report date mới nhất cho nhiều job trong 1 query: {job_id: "YYYY-MM-DD HH:MM"}."""
        from sqlalchemy import func
        from app.routers.v1.agent_reports.models.relational import Report

        if not job_ids:
            return {}
        stmt = (
            select(Report.job_id, func.max(Report.report_date))
            .where(Report.job_id.in_(job_ids))
            .group_by(Report.job_id)
        )
        result = await self.db.execute(stmt)
        return {
            job_id: dt.strftime("%Y-%m-%d %H:%M") if dt else "Never"
            for job_id, dt in result.all()
        }

    async def get_latest_report_date(self, job_id: int) -> Optional[str]:
        from app.routers.v1.agent_reports.models.relational import Report
        stmt = select(Report.report_date).where(Report.job_id == job_id).order_by(Report.report_date.desc()).limit(1)
        result = await self.db.execute(stmt)
        dt = result.scalars().first()
        if dt:
            return dt.strftime("%Y-%m-%d %H:%M")
        return "Never"
