from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Text, JSON
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
from app.core.database import Base

class Report(Base):
    __tablename__ = "reports"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    
    # Context (Trigger source)
    message_id = Column(Integer, ForeignKey("chat_messages.id"), nullable=True) # Attached to a specific AI reply
    job_id = Column(Integer, ForeignKey("jobs.id"), nullable=True) # Generated by an automated job
    
    ticker = Column(String, index=True, nullable=False)
    status = Column(String, default="running") # running, completed, failed
    report_date = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    
    # Financial fields (Nullable until completed)
    current_price = Column(Float, nullable=True)
    change = Column(Float, nullable=True) # Percent change today or from entry
    agents_count = Column(Integer, nullable=True)
    duration = Column(String, nullable=True) # e.g. "45s", "1m 12s"
    recommendation = Column(String, nullable=True) # BUY, HOLD, SELL
    confidence = Column(Integer, nullable=True) # 0-100
    target_price = Column(Float, nullable=True)
    stop_loss = Column(Float, nullable=True)
    risk_reward = Column(Float, nullable=True)
    summary = Column(Text, nullable=True)
    bull_points = Column(JSON, nullable=True) # JSON encoded list
    bear_points = Column(JSON, nullable=True) # JSON encoded list
    
    # Note: Detailed logs and stats (llm_calls, tokens, log streams) are now stored in MongoDB 
    # under the AgentLogs and TokenUsages collections using this report.id as the reference.

    # Relationships
    user = relationship("User", back_populates="reports")
    message = relationship("ChatMessage", back_populates="report")
    job = relationship("Job", back_populates="reports")
    
    agent_outputs = relationship("ReportAgentOutput", back_populates="report", cascade="all, delete-orphan")
    forecasts = relationship("ReportForecast", back_populates="report", cascade="all, delete-orphan")
    deliveries = relationship("ReportDelivery", back_populates="report", cascade="all, delete-orphan")


class ReportAgentOutput(Base):
    __tablename__ = "report_agent_outputs"

    id = Column(Integer, primary_key=True, index=True)
    report_id = Column(Integer, ForeignKey("reports.id"))
    team_name = Column(String, nullable=False) # Analyst, Research, Execution
    agent_name = Column(String, nullable=False)
    recommendation = Column(String, nullable=False)
    confidence = Column(Integer, nullable=False)
    summary = Column(Text, nullable=False)

    report = relationship("Report", back_populates="agent_outputs")


class ReportForecast(Base):
    __tablename__ = "report_forecasts"

    id = Column(Integer, primary_key=True, index=True)
    report_id = Column(Integer, ForeignKey("reports.id"))
    day_offset = Column(String, nullable=False) # e.g. "D+1", "D+2"
    price_low = Column(Float, nullable=True)
    price_high = Column(Float, nullable=True)
    price_target = Column(Float, nullable=True)
    signal = Column(String, nullable=False) # UP, DOWN, FLAT

    report = relationship("Report", back_populates="forecasts")


class ReportDelivery(Base):
    __tablename__ = "report_deliveries"

    id = Column(Integer, primary_key=True, index=True)
    report_id = Column(Integer, ForeignKey("reports.id"), nullable=False)
    channel = Column(String, nullable=False) # EMAIL, TELEGRAM
    recipient = Column(String, nullable=False) # email address or chat id
    trigger_source = Column(String, nullable=False) # AUTO_JOB, MANUAL_CLICK, BOT_COMMAND
    status = Column(String, default="PENDING") # PENDING, SUCCESS, FAILED
    error_message = Column(String, nullable=True)
    sent_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    report = relationship("Report", back_populates="deliveries")
