"use client"

import React, { createContext, useContext, useState, useEffect } from "react"

export type Language = "en" | "vi"

const translations = {
  en: {
    // Sidebar
    "sidebar.features": "Features",
    "sidebar.system": "System",
    "sidebar.home": "Home",
    "sidebar.agents": "Agents",
    "sidebar.reports": "Report History",
    "sidebar.jobs": "Scheduled Jobs",
    "sidebar.analyst": "Analyst System",
    "sidebar.reporthistory": "Report History",
    "sidebar.scheduledjobs": "Scheduled Jobs",
    "sidebar.analystsystem": "Analyst System",
    "sidebar.settings": "Settings",
    "sidebar.title": "Trading Agents VN",
    "sidebar.subtitle": "AI Finance System",

    // Dashboard (Analyst Page)
    "dashboard.title": "Dashboard",
    "dashboard.activeAgents": "Active Trading Agents",
    "dashboard.newlyDeployed": "+3 newly deployed this week",
    "dashboard.activeStrategies": "Across 4 active strategies",
    "dashboard.reportsGenerated": "Reports Generated",
    "dashboard.increasedVolume": "Increased processing volume",
    "dashboard.coverageExpanding": "Analysis coverage expanding",
    "dashboard.systemUptime": "System Uptime",
    "dashboard.stableEngine": "Stable engine performance",
    "dashboard.zeroDropped": "Zero dropped connections",
    "dashboard.apiInferences": "API Inferences (24h)",
    "dashboard.steadyUsage": "Steady LLM usage volume",
    "dashboard.tokenConsumption": "Token consumption nominal",
    "dashboard.optimal": "Optimal",
    "dashboard.processingVolume": "Agent Processing Volume",
    "dashboard.inferenceOverTime": "Inference volume over time",
    "dashboard.deepThink": "Deep Think",
    "dashboard.quickThink": "Quick Think",
    "dashboard.activeProtocols": "Active Protocols",
    "dashboard.agentLogs": "Agent Logs",
    "dashboard.reviewQueue": "Review Queue",
    "dashboard.completedTasks": "Completed Tasks",
    "dashboard.customizeColumns": "Customize Columns",
    "dashboard.columns": "Columns",
    "dashboard.addSection": "Add Section",
    "dashboard.rowsPerPage": "Rows per page",
    "dashboard.pageOf": "Page {page} of {total}",
    "dashboard.noResults": "No results.",
    "dashboard.rowsSelected": "{selected} of {total} row(s) selected.",
    "dashboard.last3months": "Last 3 months",
    "dashboard.last30days": "Last 30 days",
    "dashboard.last7days": "Last 7 days",
    "dashboard.selectView": "Select a view",
    "dashboard.colHeader": "Header",
    "dashboard.colType": "Section Type",
    "dashboard.colStatus": "Status",
    "dashboard.colTarget": "Target",
    "dashboard.colLimit": "Limit",
    "dashboard.colReviewer": "Reviewer",
    "dashboard.firstPage": "Go to first page",
    "dashboard.prevPage": "Go to previous page",
    "dashboard.nextPage": "Go to next page",
    "dashboard.lastPage": "Go to last page",

    // Home Page
    "home.badge": "VERSION 0.2.5",
    "home.title": "TradingAgents VN",
    "home.description": "An AI-powered multi-agent financial trading framework mirroring real-world trading desks. Deploying specialized LLM agents from research analysts to risk managers cooperating to beat the market.",
    "home.runSim": "Run Simulation Now",
    "home.manageSchedules": "Manage Schedules",
    "home.workflowTitle": "Standard Multi-Agent Workflow",
    "home.workflowDesc": "Click on each phase to discover the agents, roles, and collaborative decision pipeline.",
    "home.techTitle": "Framework Tech",
    "home.techState": "State Persistence",
    "home.techStateDesc": "Utilizes SQLite Database checkpoints powered by LangGraph, enabling recovery or resume from intermediate crashed steps.",
    "home.techMemory": "Self-Correction & Memory",
    "home.techMemoryDesc": "Feeds realized returns of past decisions into the Portfolio Manager prompt for continuous optimization.",
    "home.goConsole": "Go to Command Center",
    "home.teamsTitle": "Core Agent Teams",
    "home.teamsDesc": "Each team mirrors standard investment bank structures.",
    "home.teamAnalystTitle": "1. Analyst Team",
    "home.teamAnalystDesc": "Ingests technical indicators, macroeconomic updates, news stories, and stock chatter into a single, comprehensive market reading.",
    "home.teamResearchTitle": "2. Research Team",
    "home.teamResearchDesc": "Employs structured debates between Bull and Bear researchers to challenge bias and balance risk, managed by the Research Manager.",
    "home.teamTraderTitle": "3. Trader Agent",
    "home.teamTraderDesc": "Synthesizes reports from research and analysts to construct order proposals, defining entry, exit targets and timing.",
    "home.teamPortfolioTitle": "4. Portfolio & Risk",
    "home.teamPortfolioDesc": "Enforces position sizing bounds, verifies drawdown risk, and grants final execution sign-off before trades land on-chain.",
    "home.step.data.label": "Data Ingestion",
    "home.step.data.desc": "Fetches live price data, technical indicators, and social sentiment (Reddit, X, StockTwits).",
    "home.step.analysts.label": "Analyst Team",
    "home.step.analysts.desc": "Specialized agents run parallel research on Fundamentals, News, Sentiment & Technicals.",
    "home.step.researchers.label": "Debate & Research",
    "home.step.researchers.desc": "Bull and Bear Researchers debate risks and upside. Research Manager weights the final consensus.",
    "home.step.risk.label": "Risk & Execution",
    "home.step.risk.desc": "Trader proposes sizing. Risk Management verifies bounds and Portfolio Manager signs off.",
    "home.step.exchange.label": "Order Execution",
    "home.step.exchange.desc": "Sends the approved transaction order to the Simulated Exchange broker for execution.",
    "home.activeAgents": "Active Agents in this Phase:",

    // Reports Page
    "reports.searchPlaceholder": "Search ticker...",
    "reports.reportsCount": "reports",
    "reports.overallBias": "Overall bias",
    "reports.analyses": "analyses",
    "reports.agentsPerRun": "agents / run",
    "reports.listTitle": "Analysis Reports — Click to view details",
    "reports.latest": "Latest",
    "reports.confidence": "AI Confidence",
    "reports.targetPrice": "Target Price",
    "reports.stopLoss": "Stop Loss",
    "reports.riskReward": "R/R Ratio",
    "reports.reAnalyze": "Re-analyze",
    "reports.overview": "overview",
    "reports.agents": "agents",
    "reports.forecast": "forecast",
    "reports.priceOnAnalysis": "on analysis date",
    "reports.aiSummary": "AI Summary",
    "reports.bullCase": "Bull Case",
    "reports.bearCase": "Bear Case",
    "reports.forecastTitle": "7-day price forecast from",
    "reports.entryPrice": "Entry price",
    "reports.projectedReturn": "7-day projected return",
    "reports.analystTeam": "Analyst Team",
    "reports.researchTeam": "Research Team",
    "reports.executionTeam": "Execution Team",
    "reports.fundamentals": "Fundamentals",
    "reports.sentiment": "Sentiment",
    "reports.newsAnalyst": "News Analyst",
    "reports.technicals": "Technicals",
    "reports.bullResearcher": "Bull Researcher",
    "reports.bearResearcher": "Bear Researcher",
    "reports.researchManager": "Research Manager",
    "reports.riskManagement": "Risk Management",
    "reports.portfolioManager": "Portfolio Manager",
    "reports.trader": "Trader",
    "reports.delete": "Delete",
    "reports.deleteReport": "Delete Report",
    "reports.deleteTicker": "Delete Ticker",
    "reports.confirmDeleteReportTitle": "Delete Report",
    "reports.confirmDeleteReportDesc": "Are you sure you want to hide this report? It will remain in your chat history.",
    "reports.confirmDeleteTickerTitle": "Delete Ticker",
    "reports.confirmDeleteTickerDesc": "Are you sure you want to hide all reports for this ticker? They will remain in your chat history.",
    "reports.reportDeletedSuccess": "Report deleted successfully",
    "reports.tickerDeletedSuccess": "Ticker deleted successfully",
    "reports.deleteFailed": "Failed to delete",

    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.error": "An error occurred",

    // Research / Agents Page
    "research.title": "AI Trading Agents Research Console",
    "research.subtitle": "Configure and trigger multi-agent analysis workflows on global assets in real time.",
    "research.settings": "Analysis Settings",
    "research.ticker": "Ticker Symbol",
    "research.tickerPlaceholder": "e.g. AAPL, BTC-USD, HPG",
    "research.model": "LLM backbone",
    "research.rounds": "Debate rounds",
    "research.depth": "Research Depth",
    "research.depthFast": "Fast (1 debate round)",
    "research.depthStandard": "Standard (2 debate rounds)",
    "research.depthDeep": "Deep Think (3+ debate rounds)",
    "research.startBtn": "Start Multi-Agent Analysis",
    "research.running": "Running Simulation...",
    "research.pipeline": "Pipeline Execution Log",
    "research.cli": "CLI Dialog Logs",
    "research.agentsChat": "Agents Team Chat",
    "research.allLogs": "All Logs",
    "research.analysts": "Analysts",
    "research.researchers": "Researchers",
    "research.trader": "Trader",
    "research.pm": "Portfolio Manager",
    "research.risk": "Risk",
    "research.welcomeTitle": "Trading Console Ready",
    "research.welcomeDesc": "AI Agents Pipeline is standing by. Select a quick action or input your custom trading request below.",
    "research.welcomePromptPlaceholder": "Tell AI Agents what you want to research or trade...",
    "research.disclaimer": "AI Agents may produce inaccurate information. Please verify important investment decisions.",
    "research.provider": "AI Provider",
    "research.activeTeams": "Active Analyst Teams",
    "research.reasoningEffort": "Reasoning Effort",
    "research.depthShallow": "Shallow (Fast)",
    "research.depthMedium": "Medium (Balanced)",
    "research.depthDeepOption": "Deep (Comprehensive)",
    "research.effortLow": "Low (Heuristic)",
    "research.effortMedium": "Medium (Standard)",
    "research.effortHigh": "High (Deep Debate)",
    "research.tabBasic": "Basic",
    "research.tabAdvanced": "Advanced",
    "research.temperature": "Temperature",
    "research.topP": "Top P",
    "research.topK": "Top K",
    "research.maxTokens": "Max Tokens",
    "research.maxRetries": "Max Retries",

    // Jobs Page
    "jobs.title": "Scheduled Trading Jobs",
    "jobs.subtitle": "Control Center for multi-agent automated pipelines.",
    "jobs.create": "Create Schedule",
    "jobs.activeJobs": "Active Jobs",
    "jobs.completedJobs": "Completed Runs",
    "jobs.successRate": "Success Rate",
    "jobs.pipelineActivity": "Pipeline Activity (Last 7 Days)",
    "jobs.runDuration": "Avg Run Duration",
    "jobs.searchPlaceholder": "Search scheduled jobs...",
    "jobs.tableTicker": "Ticker",
    "jobs.tableSchedule": "Schedule",
    "jobs.tableStatus": "Status",
    "jobs.tableLastRun": "Last Run",
    "jobs.tableNextRun": "Next Run",
    "jobs.tableHistory": "Recent Runs",
    "jobs.tableActions": "Actions",
    "jobs.viewLogs": "View Logs",

    // Deliveries Page
    "sidebar.deliveries": "Deliveries",
    "deliveries.title": "Delivery History",
    "deliveries.subtitle": "Track automated and manual report distributions via Email and Telegram.",
    "deliveries.refresh": "Refresh Logs",
    "deliveries.manualBroadcast": "Manual Broadcast",
    "deliveries.search": "Search by Ticker or Recipient...",
    "deliveries.status": "Status",
    "deliveries.allStatuses": "All Statuses",
    "deliveries.success": "Success",
    "deliveries.failed": "Failed",
    "deliveries.pending": "Pending",
    "deliveries.table.id": "Delivery ID",
    "deliveries.table.target": "Target",
    "deliveries.table.channel": "Channel",
    "deliveries.table.source": "Trigger Source",
    "deliveries.table.status": "Status",
    "deliveries.table.time": "Time",
    "deliveries.table.actions": "Actions",
    "deliveries.table.noLogs": "No delivery logs found.",
    "deliveries.action.view": "View",
    "deliveries.action.resend": "Resend",
    "deliveries.dialog.title": "Sent Report:",
    "deliveries.dialog.deliveredTo": "Delivered to",
    "deliveries.dialog.via": "via",
    "deliveries.dialog.on": "on",
  },
  vi: {
    // Sidebar
    "sidebar.features": "Tính năng",
    "sidebar.system": "Hệ thống",
    "sidebar.home": "Trang chủ",
    "sidebar.agents": "Agents Chat",
    "sidebar.reports": "Lịch Sử Báo Cáo",
    "sidebar.jobs": "Lịch Trình Chạy",
    "sidebar.analyst": "Bảng Thống Kê",
    "sidebar.reporthistory": "Lịch Sử Báo Cáo",
    "sidebar.scheduledjobs": "Lịch Trình Chạy",
    "sidebar.analystsystem": "Bảng Thống Kê",
    "sidebar.settings": "Cài đặt",
    "sidebar.title": "Trading Agents VN",
    "sidebar.subtitle": "Hệ Thống Tài Chính AI",

    // Dashboard (Analyst Page)
    "dashboard.title": "Bảng Thống Kê Hệ Thống",
    "dashboard.activeAgents": "Trading Agents Hoạt Động",
    "dashboard.newlyDeployed": "+3 mới triển khai tuần này",
    "dashboard.activeStrategies": "Trên 4 chiến thuật kích hoạt",
    "dashboard.reportsGenerated": "Báo Cáo Đã Tạo",
    "dashboard.increasedVolume": "Tăng dung lượng xử lý",
    "dashboard.coverageExpanding": "Mở rộng độ phủ phân tích",
    "dashboard.systemUptime": "Thời Gian Hoạt Động Hệ Thống",
    "dashboard.stableEngine": "Hiệu năng động cơ ổn định",
    "dashboard.zeroDropped": "Không mất kết nối",
    "dashboard.apiInferences": "API Inference (24h)",
    "dashboard.steadyUsage": "Khối lượng dùng LLM ổn định",
    "dashboard.tokenConsumption": "Tiêu thụ token bình thường",
    "dashboard.optimal": "Tối Ưu",
    "dashboard.processingVolume": "Khối Lượng Xử Lý Của Agent",
    "dashboard.inferenceOverTime": "Khối lượng inference theo thời gian",
    "dashboard.deepThink": "Suy Nghĩ Sâu",
    "dashboard.quickThink": "Suy Nghĩ Nhanh",
    "dashboard.activeProtocols": "Giao Thức Hoạt Động",
    "dashboard.agentLogs": "Nhật Ký Agent",
    "dashboard.reviewQueue": "Hàng Đợi Đánh Giá",
    "dashboard.completedTasks": "Nhiệm Vụ Hoàn Thành",
    "dashboard.customizeColumns": "Tùy Chỉnh Cột",
    "dashboard.columns": "Cột Hiển Thị",
    "dashboard.addSection": "Thêm Nhóm",
    "dashboard.rowsPerPage": "Số dòng mỗi trang",
    "dashboard.pageOf": "Trang {page} trên {total}",
    "dashboard.noResults": "Không có kết quả.",
    "dashboard.rowsSelected": "Đã chọn {selected} trên {total} dòng.",
    "dashboard.last3months": "3 tháng qua",
    "dashboard.last30days": "30 ngày qua",
    "dashboard.last7days": "5 ngày qua",
    "dashboard.selectView": "Chọn chế độ xem",
    "dashboard.colHeader": "Tiêu Đề",
    "dashboard.colType": "Loại Nhóm",
    "dashboard.colStatus": "Trạng Thái",
    "dashboard.colTarget": "Mục Tiêu",
    "dashboard.colLimit": "Giới Hạn",
    "dashboard.colReviewer": "Người Duyệt",
    "dashboard.firstPage": "Đến trang đầu",
    "dashboard.prevPage": "Quay lại trang trước",
    "dashboard.nextPage": "Đến trang tiếp theo",
    "dashboard.lastPage": "Đến trang cuối",

    // Home Page
    "home.badge": "PHIÊN BẢN 0.2.5",
    "home.title": "TradingAgents VN",
    "home.description": "Hệ thống giao dịch đa tác tử AI mô phỏng mô hình phòng giao dịch thực tế. Các agent AI từ phân tích, nghiên cứu đến quản trị rủi ro phối hợp cùng nhau để tối ưu hóa quyết định đầu tư.",
    "home.runSim": "Chạy Phân Tích Ngay",
    "home.manageSchedules": "Quản Lý Lịch Trình",
    "home.workflowTitle": "Quy Trình Hoạt Động Chuẩn",
    "home.workflowDesc": "Bấm vào từng giai đoạn để khám phá các agent, vai trò và quy trình ra quyết định đầu tư.",
    "home.techTitle": "Công Nghệ Nền Tảng",
    "home.techState": "Lưu Trữ Trạng Thái",
    "home.techStateDesc": "Sử dụng checkpoint SQLite qua LangGraph giúp phục hồi hoặc tiếp tục chạy từ các bước bị gián đoạn mà không cần làm lại từ đầu.",
    "home.techMemory": "Tự Sửa Lỗi & Trí Nhớ",
    "home.techMemoryDesc": "Tự động phân tích hiệu quả giao dịch thực tế trong quá khứ để đưa vào prompt của Portfolio Manager nhằm tối ưu quyết định tiếp theo.",
    "home.goConsole": "Đến Trung Tâm Phân Tích",
    "home.teamsTitle": "Các Đội Agent Cốt Lõi",
    "home.teamsDesc": "Mỗi đội phản ánh cấu trúc chuẩn của một quỹ đầu tư tài chính chuyên nghiệp.",
    "home.teamAnalystTitle": "1. Đội Phân Tích",
    "home.teamAnalystDesc": "Thu thập chỉ báo kỹ thuật, dữ liệu vĩ mô, tin tức toàn cầu và thảo luận mạng xã hội thành báo cáo tổng hợp.",
    "home.teamResearchTitle": "2. Đội Nghiên Cứu",
    "home.teamResearchDesc": "Tổ chức tranh biện đối lập giữa hai luồng quan điểm Bull (tích cực) và Bear (tiêu cực) để làm rõ rủi ro, kiểm soát bởi Research Manager.",
    "home.teamTraderTitle": "3. Đội Giao Dịch",
    "home.teamTraderDesc": "Tổng hợp kết quả nghiên cứu để đề xuất phương án mua/bán, điểm vào lệnh, cắt lỗ và quy mô giao dịch.",
    "home.teamPortfolioTitle": "4. Quản Trị & Danh Mục",
    "home.teamPortfolioDesc": "Đánh giá biến động thị trường, thanh khoản để phê duyệt/từ chối giao dịch và thực thi giao dịch trên sàn.",
    "home.step.data.label": "Thu Thập Dữ Liệu",
    "home.step.data.desc": "Truy xuất dữ liệu giá thời gian thực, chỉ báo kỹ thuật, tin tức và mạng xã hội (Reddit, X, StockTwits).",
    "home.step.analysts.label": "Đội Phân Tích",
    "home.step.analysts.desc": "Các Agent phân tích chuyên biệt chạy song song nghiên cứu Báo cáo tài chính, Tin tức, Mạng xã hội & Chỉ báo kỹ thuật.",
    "home.step.researchers.label": "Tranh Luận & Nghiên Cứu",
    "home.step.researchers.desc": "Agent Bull và Bear tranh luận về các cơ hội & rủi ro dưới sự kiểm soát và tổng hợp của Research Manager.",
    "home.step.risk.label": "Quản Trị Rủi Ro & Lệnh",
    "home.step.risk.desc": "Trader đề xuất lượng giao dịch. Quản trị rủi ro kiểm tra giới hạn an toàn và Portfolio Manager ký duyệt cuối cùng.",
    "home.step.exchange.label": "Thực Thi Giao Dịch",
    "home.step.exchange.desc": "Gửi yêu cầu giao dịch đã được phê duyệt trực tiếp đến sàn giao dịch giả lập.",
    "home.activeAgents": "Các Agent Hoạt Động Trong Giai Đoạn Này:",

    // Reports Page
    "reports.searchPlaceholder": "Tìm mã giao dịch...",
    "reports.reportsCount": "báo cáo",
    "reports.overallBias": "Xu hướng tổng quan",
    "reports.analyses": "lượt phân tích",
    "reports.agentsPerRun": "agents / lượt",
    "reports.listTitle": "Danh Sách Báo Cáo — Bấm để xem chi tiết",
    "reports.latest": "Mới nhất",
    "reports.confidence": "Độ Tin Cậy AI",
    "reports.targetPrice": "Giá Mục Tiêu",
    "reports.stopLoss": "Cắt Lỗ",
    "reports.riskReward": "Tỷ Lệ R/R",
    "reports.reAnalyze": "Phân Tích Lại",
    "reports.overview": "tổng quan",
    "reports.agents": "agents",
    "reports.forecast": "dự báo",
    "reports.priceOnAnalysis": "tại ngày phân tích",
    "reports.aiSummary": "Tóm Tắt Của AI",
    "reports.bullCase": "Quan Điểm Tăng (Bull)",
    "reports.bearCase": "Quan Điểm Giảm (Bear)",
    "reports.forecastTitle": "Dự đoán giá 5 ngày tính từ",
    "reports.entryPrice": "Giá vào lệnh",
    "reports.projectedReturn": "Lợi nhuận dự kiến 7 ngày",
    "reports.analystTeam": "Đội Phân Tích",
    "reports.researchTeam": "Đội Nghiên Cứu",
    "reports.executionTeam": "Đội Thực Thi",
    "reports.fundamentals": "Cơ Bản",
    "reports.sentiment": "Tâm Lý Thị Trường",
    "reports.newsAnalyst": "Tin Tức",
    "reports.technicals": "Kỹ Thuật",
    "reports.bullResearcher": "Nghiên Cứu Tăng",
    "reports.bearResearcher": "Nghiên Cứu Giảm",
    "reports.researchManager": "Quản Lý Nghiên Cứu",
    "reports.riskManagement": "Quản Trị Rủi Ro",
    "reports.portfolioManager": "Quản Lý Danh Mục",
    "reports.trader": "Giao Dịch",
    "reports.delete": "Xóa",
    "reports.deleteReport": "Xóa Báo Cáo",
    "reports.deleteTicker": "Xóa Mã Tài Sản",
    "reports.confirmDeleteReportTitle": "Xóa Báo Cáo",
    "reports.confirmDeleteReportDesc": "Bạn có chắc chắn muốn ẩn báo cáo này không? Nội dung vẫn sẽ được giữ lại trong lịch sử chat.",
    "reports.confirmDeleteTickerTitle": "Xóa Mã Tài Sản",
    "reports.confirmDeleteTickerDesc": "Bạn có chắc chắn muốn ẩn TẤT CẢ báo cáo của mã này không? Nội dung vẫn sẽ được giữ lại trong lịch sử chat.",
    "reports.reportDeletedSuccess": "Xóa báo cáo thành công",
    "reports.tickerDeletedSuccess": "Xóa mã tài sản thành công",
    "reports.deleteFailed": "Xóa thất bại",

    "common.cancel": "Hủy",
    "common.confirm": "Xác nhận",
    "common.error": "Đã xảy ra lỗi",

    // Research / Agents Page
    "research.title": "Bảng Điều Khiển Trading Agents AI",
    "research.subtitle": "Cấu hình và kích hoạt quy trình phân tích tự động đa agent trên các tài sản tài chính thời gian thực.",
    "research.settings": "Cấu Hình Phân Tích",
    "research.ticker": "Mã Tài Sản (Ticker)",
    "research.tickerPlaceholder": "ví dụ: AAPL, BTC-USD, HPG",
    "research.model": "Mô hình LLM chính",
    "research.rounds": "Số vòng tranh luận",
    "research.depth": "Độ Sâu Nghiên Cứu",
    "research.depthFast": "Nhanh (1 vòng tranh luận)",
    "research.depthStandard": "Tiêu chuẩn (2 vòng tranh luận)",
    "research.depthDeep": "Chuyên sâu (3+ vòng)",
    "research.startBtn": "Bắt Đầu Phân Tích AI",
    "research.running": "Đang phân tích...",
    "research.pipeline": "Luồng Chạy Pipeline",
    "research.cli": "Nhật Ký CLI",
    "research.agentsChat": "Đội Ngũ Agent Thảo Luận",
    "research.allLogs": "Tất Cả Logs",
    "research.analysts": "Phân Tích",
    "research.researchers": "Nghiên Cứu",
    "research.trader": "Giao Dịch",
    "research.pm": "Portfolio Manager",
    "research.risk": "Quản Trị Rủi Ro",
    "research.welcomeTitle": "Hệ Thống Agent Đã Sẵn Sàng",
    "research.welcomeDesc": "Luồng xử lý của các Agent AI đang ở trạng thái chờ lệnh. Vui lòng chọn thao tác nhanh bên dưới hoặc nhập yêu cầu phân tích của bạn.",
    "research.welcomePromptPlaceholder": "Nhập yêu cầu phân tích hoặc mã chứng khoán/crypto mà bạn muốn giao dịch...",
    "research.disclaimer": "Các Agent AI có thể đưa ra thông tin không chính xác. Vui lòng xác thực trước khi đưa ra quyết định đầu tư thực tế.",
    "research.provider": "Nhà cung cấp AI",
    "research.activeTeams": "Đội Phân Tích Kích Hoạt",
    "research.reasoningEffort": "Nỗ Lực Suy Luận",
    "research.depthShallow": "Sơ lược (Nhanh)",
    "research.depthMedium": "Trung bình (Tiêu chuẩn)",
    "research.depthDeepOption": "Sâu (Toàn diện)",
    "research.effortLow": "Thấp (Heuristic)",
    "research.effortMedium": "Vừa (Cân bằng)",
    "research.effortHigh": "Cao (Tranh luận sâu)",
    "research.tabBasic": "Cơ Bản",
    "research.tabAdvanced": "Nâng Cao",
    "research.temperature": "Nhiệt Độ (Temperature)",
    "research.topP": "Top P",
    "research.topK": "Top K",
    "research.maxTokens": "Giới Hạn Token",
    "research.maxRetries": "Số Lần Thử Lại",

    // Jobs Page
    "jobs.title": "Lịch Trình Phân Tích",
    "jobs.subtitle": "Trung tâm kiểm soát lịch phân tích định kỳ của các agent AI.",
    "jobs.create": "Tạo Lịch Trình",
    "jobs.activeJobs": "Đang Kích Hoạt",
    "jobs.completedJobs": "Lượt Chạy Hoàn Thành",
    "jobs.successRate": "Tỷ Lệ Thành Công",
    "jobs.pipelineActivity": "Tần Suất Hoạt Động (7 Ngày Qua)",
    "jobs.runDuration": "Thời Gian Chạy Trung Bình",
    "jobs.searchPlaceholder": "Tìm lịch trình...",
    "jobs.tableTicker": "Mã Tài Sản",
    "jobs.tableSchedule": "Lịch Trình",
    "jobs.tableStatus": "Trạng Thái",
    "jobs.tableLastRun": "Lần Chạy Trước",
    "jobs.tableNextRun": "Lần Chạy Tiếp theo",
    "jobs.tableHistory": "Lịch Sử Chạy",
    "jobs.tableActions": "Hành Động",
    "jobs.viewLogs": "Xem Logs",

    // Deliveries Page
    "sidebar.deliveries": "Quản lý gửi Email",
    "deliveries.title": "Quản lý gửi Email",
    "deliveries.subtitle": "Theo dõi các lượt gửi báo cáo tự động và thủ công qua Email và Telegram.",
    "deliveries.refresh": "Làm Mới",
    "deliveries.manualBroadcast": "Gửi Thủ Công",
    "deliveries.search": "Tìm mã CK hoặc người nhận...",
    "deliveries.status": "Trạng Thái",
    "deliveries.allStatuses": "Tất cả trạng thái",
    "deliveries.success": "Thành công",
    "deliveries.failed": "Thất bại",
    "deliveries.pending": "Đang chờ",
    "deliveries.table.id": "Mã Gửi",
    "deliveries.table.target": "Mục Tiêu",
    "deliveries.table.channel": "Kênh",
    "deliveries.table.source": "Nguồn Gửi",
    "deliveries.table.status": "Trạng Thái",
    "deliveries.table.time": "Thời Gian",
    "deliveries.table.actions": "Thao Tác",
    "deliveries.table.noLogs": "Không tìm thấy lịch sử phân phối nào.",
    "deliveries.action.view": "Xem Báo Cáo",
    "deliveries.action.resend": "Gửi Lại",
    "deliveries.dialog.title": "Báo Cáo Đã Gửi:",
    "deliveries.dialog.deliveredTo": "Đã gửi đến",
    "deliveries.dialog.via": "qua",
    "deliveries.dialog.on": "vào lúc",
  }
}

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: keyof typeof translations.en) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

function getInitialLanguage(): Language {
  // Always return 'en' during SSR to match the server
  if (typeof window === "undefined") return "en"
  // Return 'en' on the first client render too, then we update it in an effect
  return "en"
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage)
  const [isMounted, setIsMounted] = useState(false)

  useEffect(() => {
    const stored = localStorage.getItem("app-language") as Language
    if (stored === "en" || stored === "vi") {
      setLanguageState(stored)
    }
    setIsMounted(true)
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    if (typeof window !== "undefined") {
      localStorage.setItem("app-language", lang)
    }
  }

  const t = (key: keyof typeof translations.en): string => {
    // To avoid hydration mismatch, always use English until mounted
    const currentLang = isMounted ? language : "en"
    const dict = translations[currentLang] || translations.en
    return dict[key] || translations.en[key] || String(key)
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
